services:
  - type: web
    name: anivo-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 2 --worker-class sync
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0

  - type: worker
    name: anivo-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
